#!/bin/bash
# =====================================================
#  EntroGuard — Deploy to Raspberry Pi
#  Run this on your LAPTOP after training the model
#
#  Usage:
#    bash deploy.sh
#
#  Requirements:
#    - Laptop and Pi both connected to SAME mobile hotspot
#    - SSH enabled on Pi (sudo raspi-config → Interface → SSH)
#    - xgb_model.pkl and scaler.pkl generated by train_model.py
# =====================================================

# ─────────────────────────────────────────────
# ⚙️  CONFIG — Edit these before running
# ─────────────────────────────────────────────

PI_USER="pi"                      # Pi username (default: pi)
PI_IP="192.168.XXX.XXX"          # ← Pi's IP on mobile hotspot
                                  #   find it: hostname -I  (run on Pi)
PI_DIR="/home/pi/entroguard"      # deployment folder on Pi
SSH_KEY=""                        # optional SSH key path e.g. ~/.ssh/id_rsa

# ─────────────────────────────────────────────
# COLORS
# ─────────────────────────────────────────────

GREEN='\033[0;32m'; RED='\033[0;31m'
YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

echo ""
echo -e "${CYAN}====================================================${NC}"
echo -e "${CYAN}  EntroGuard — Deploy to Raspberry Pi${NC}"
echo -e "${CYAN}  Mobile Hotspot Edition${NC}"
echo -e "${CYAN}====================================================${NC}"
echo ""

# ─────────────────────────────────────────────
# VALIDATE CONFIG
# ─────────────────────────────────────────────

if [[ "$PI_IP" == "192.168.XXX.XXX" ]]; then
    echo -e "${RED}❌ Set PI_IP in deploy.sh first!${NC}"
    echo "   On your Pi run: hostname -I"
    exit 1
fi

SSH_CMD="ssh"; SCP_CMD="scp"
if [ -n "$SSH_KEY" ]; then
    SSH_CMD="ssh -i $SSH_KEY"; SCP_CMD="scp -i $SSH_KEY"
fi

# ─────────────────────────────────────────────
# STEP 1 — TRAIN MODEL IF NEEDED
# ─────────────────────────────────────────────

echo -e "${YELLOW}[1/4] Checking model files...${NC}"
if [ ! -f "model/xgb_model.pkl" ] || [ ! -f "model/scaler.pkl" ]; then
    echo "   Training model..."
    cd model && python train_model.py && cd ..
    [ $? -ne 0 ] && echo -e "${RED}❌ Training failed${NC}" && exit 1
else
    echo -e "${GREEN}   ✅ xgb_model.pkl found${NC}"
    echo -e "${GREEN}   ✅ scaler.pkl found${NC}"
fi

# ─────────────────────────────────────────────
# STEP 2 — CREATE DIRECTORY ON PI
# ─────────────────────────────────────────────

echo ""
echo -e "${YELLOW}[2/4] Connecting to Pi at ${PI_IP}...${NC}"
$SSH_CMD ${PI_USER}@${PI_IP} "mkdir -p ${PI_DIR}"

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Cannot reach Pi at ${PI_IP}${NC}"
    echo "   Check:"
    echo "   • Both devices on same mobile hotspot"
    echo "   • Hotspot set to 2.4GHz"
    echo "   • SSH enabled on Pi: sudo raspi-config"
    exit 1
fi
echo -e "${GREEN}   ✅ Connected!${NC}"

# ─────────────────────────────────────────────
# STEP 3 — COPY FILES
# ─────────────────────────────────────────────

echo ""
echo -e "${YELLOW}[3/4] Copying files to Pi...${NC}"

declare -A FILES=(
    ["model/xgb_model.pkl"]="${PI_DIR}/xgb_model.pkl"
    ["model/scaler.pkl"]="${PI_DIR}/scaler.pkl"
    ["pi/pi_receiver.py"]="${PI_DIR}/pi_receiver.py"
    ["dashboard/streamlit_dashboard_v2.py"]="${PI_DIR}/streamlit_dashboard_v2.py"
)

for SRC in "${!FILES[@]}"; do
    DEST="${FILES[$SRC]}"
    if [ -f "$SRC" ]; then
        $SCP_CMD "$SRC" "${PI_USER}@${PI_IP}:${DEST}"
        [ $? -eq 0 ] && echo -e "${GREEN}   ✅ $SRC${NC}" \
                      || echo -e "${RED}   ❌ $SRC failed${NC}"
    else
        echo -e "${YELLOW}   ⚠ $SRC not found, skipping${NC}"
    fi
done

# ─────────────────────────────────────────────
# STEP 4 — INSTALL DEPENDENCIES ON PI
# ─────────────────────────────────────────────

echo ""
echo -e "${YELLOW}[4/4] Installing dependencies on Pi...${NC}"
$SSH_CMD ${PI_USER}@${PI_IP} \
    "pip3 install xgboost scikit-learn joblib pandas numpy psutil streamlit plotly seaborn matplotlib reportlab --quiet"

[ $? -eq 0 ] && echo -e "${GREEN}   ✅ Dependencies installed${NC}" \
              || echo -e "${YELLOW}   ⚠ Some may have failed — check manually${NC}"

# ─────────────────────────────────────────────
# DONE
# ─────────────────────────────────────────────

echo ""
echo -e "${CYAN}====================================================${NC}"
echo -e "${GREEN}  ✅ Deployment Complete!${NC}"
echo -e "${CYAN}====================================================${NC}"
echo ""
echo "  On your Raspberry Pi (SSH in first):"
echo "  ssh ${PI_USER}@${PI_IP}"
echo ""
echo -e "  ${CYAN}# Terminal 1 — Detection engine:${NC}"
echo "  cd ${PI_DIR} && python3 pi_receiver.py"
echo ""
echo -e "  ${CYAN}# Terminal 2 — Dashboard:${NC}"
echo "  cd ${PI_DIR} && streamlit run streamlit_dashboard_v2.py"
echo ""
echo -e "  ${CYAN}# Open dashboard on any hotspot device:${NC}"
echo "  http://${PI_IP}:8501"
echo ""
echo -e "${CYAN}====================================================${NC}"
